name: CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3 # fetches my repo code so that workflow can work with it

    - name: install Python 3.9
      uses: actions/setup-python@v4 # get python
      with:
        python-version: '3.9'

    - name: Install dependencies #install packages for python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint # flake8 is linting... it can check the errors, mistakes and style violations of python codes
      run: |
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        black --check service
        pylint service

    - name: Run unit tests # nose looks for test*.py or *_test.py
      run: |
        nosetests --with-coverage --cover-package=service
    # building and utilisation of image are in task.yml (differently from my other projs)